### ISSUE TITLE
single line

### ISSUE THREAD

**Issue by MEHDIMYADI** [wangchenyan/LrcView#1]
Hi ChanWong21
Thank you for your best library
i have a issue for lyric view your library cant support multiline textview because in singleline lyric show is not perfect.
thanks

**Comment by ChanWong21** [comment]
Thank you!
I will add support for multi-line lyrics display in a few days.

**Comment by ChanWong21** [comment]
Hello, I have updated version 1.1.0, support multi-line lyrics display.
Also update the Gradle reference from
`me.wcy.lrcview:lrcview:latestVersion`
to
`me.wcy:lrcview:latestVersion`
Thank you.

**Comment by MEHDIMYADI** [comment]
Hi, Cool,
Thank you dr.
I soon test new lib and feedback.

**Comment by MEHDIMYADI** [comment]
Hi, ChanWong21
i tested lib.
i have issue in rtl language!
half of text show in right and no show full of text in center of layout.
that issue is only in rtl language and not have the problem in ltr language.
screenshot
![test](https://cloud.githubusercontent.com/assets/13472537/19517704/9baefffa-960f-11e6-8abb-9f7cca73e7c1.jpg)

thank you

**Comment by ChanWong21** [comment]
Hi, sorry, now I have fixed the problem, you can upgrade to version 1.2.0.
Thank you.
@MEHDIMYADI 
![device-2016-10-20-134621_](https://cloud.githubusercontent.com/assets/12638716/19547749/b589ade0-96cc-11e6-84db-1e102e40e7c8.png)

**Comment by MEHDIMYADI** [comment]
Hi, thank you for hard work.
the problem has been solved.
