### ISSUE TITLE
特定情况拖动歌词时间线不会消失

### ISSUE THREAD

**Issue by wscjy** [wangchenyan/LrcView#12]
在ViewPager中其中一页fragment内置LrcView，滑动歌词出现时间线后迅速滑向其它页，再次滑回来时时间线不会消失。

**Comment by wangchenyan** [comment]
@wscjy 你好，这个问题我会尽快修复，谢谢！

**Comment by wangchenyan** [comment]
@wscjy 你好，问题已修复，请升级最新版2.0.1，谢谢！
