### ISSUE TITLE
缺少歌词

### ISSUE THREAD

**Issue by kb18519142009** [wangchenyan/lrcview#14]
有时候会缺少第一句歌词，不知道为什么

**Comment by wangchenyan** [comment]
@kb18519142009 能否提供下歌词文件？

**Comment by bill556** [comment]
@wangchenyan LrcEntry.java 116行        
 line = line.trim();
 Matcher lineMatcher = Pattern.compile("((\\[\\d\\d:\\d\\d\\.\\d\\d\\])+)(.+)").matcher(line);
  if (!lineMatcher.matches()) {
       return null;
  }
第一次总会是matches不到歌词   返回null  导致他们第一句歌词没有显示。请查看 一下

**Comment by kb18519142009** [comment]
似乎是正则太严格了

**Comment by wangchenyan** [comment]
能提供下歌词原文本吗？

**Comment by bill556** [comment]
[00:07.14]（原唱）
[00:10.61]月儿圆，月儿亮
[00:16.62]月光照四方
[00:20.29]（月光照四方，啦啦啦啦啦）
[00:22.42]星星伴着月儿游
[00:27.84]大地换银装
[00:31.56]（大地换银装，啦啦啦啦啦）
[00:33.39]照四方
[00:40.02]……
[00:49.93]月儿圆，月儿亮
[00:55.45]月光照四方
[00:59.40]（月光照四方，啦啦啦啦啦）
[01:01.06]星星伴着月儿游
[01:06.47]大地换银装
[01:10.31]（大地换银装，啦啦啦啦啦）
[01:12.52]照四方
[01:22.40]（小朋友唱）
[01:32.11]月儿圆，月儿亮
[01:37.53]月光照四方
[01:41.56]（月光照四方，啦啦啦啦啦）
[01:43.16]星星伴着月儿游
[01:48.60]大地换银装
[01:52.63]（大地换银装，啦啦啦啦啦）
[01:54.44]照四方
[02:01.25]

**Comment by bill556** [comment]
比如原唱这一句就无法显示

**Comment by bill556** [comment]
我是通过ByUrl播放  如果看到 请关注一下

**Comment by wangchenyan** [comment]
@bill556 你好，我这边测试时可以显示的
![image](https://user-images.githubusercontent.com/12638716/71608189-4503a680-2bba-11ea-94e6-95b21c24e582.png)

**Comment by bill556** [comment]
String lrc = "http://pic.landun.tech/a55c89d2c0717124add9c5f70fb04074.lrc?download/27.%E6%9C%88%E5%9C%86%E6%9B%B2.lrc";
    String mp3 = "http://pic.landun.tech/13d5248f2ffd39b42f0874fbd84f4fb7.mp3?download/27.%E6%9C%88%E5%9C%86%E6%9B%B2.mp3";


我是在线播放的  您可以试一下吗

**Comment by bill556** [comment]
#
<img width="1103" alt="WX20191231-112652@2x" src="https://user-images.githubusercontent.com/18108636/71609066-80a16f00-2bc0-11ea-84d3-afe7885a37d4.png">
这就是第一句解析~  就是正则匹配不过，奇怪

**Comment by wangchenyan** [comment]
@bill556 utf-8转码会在开头添加\uFEFF，我处理下

**Comment by bill556** [comment]
好的 谢谢~

**Comment by wangchenyan** [comment]
@bill556 fixed on 2.1.3
