### ISSUE TITLE
希望能增加一个解析在线歌词功能

### ISSUE THREAD

**Issue by MomFeng** [wangchenyan/lrcview#15]
希望传入一个歌词的在线url就能直接解析，谢谢～
在线歌词测试地址：http://lrc.zhenxian.fm/lrc/ucJg7v6G8lnN9y1frO.lrc

**Comment by cyixlq** [comment]
当你发起get请求的时候获取的response就是这个词，一串字符串吧

**Comment by wangchenyan** [comment]
你好，已经支持，详见 README
