### ISSUE TITLE
动画效果无法正常显示(请在AOSP上测试)

### ISSUE THREAD

**Issue by ghost** [wangchenyan/lrcview#18]
在节电助手开启时动画效果无法正常显示(节电助手限制部分动画效果的使用)。

测试机型部分信息:
Android 版本: 6.0 (MRA58K)
OS: AOSP (MediaTek)

**Comment by jellybean13** [comment]
你提到的这个问题已成功修复: https://github.com/jellybean13/lrcview/commit/061378d4275c0230f031fec1b8f20c49c974bd88

**Comment by wangchenyan** [comment]
感谢 @jellybean13
