### ISSUE TITLE
加载歌词但不展示

### ISSUE THREAD

**Issue by CoolEnoughSmile** [wangchenyan/lrcview#27]
你好，请问调用loadLRc方法后歌词不展示是什么原因？能把用法步骤写再详细一些吗？谢谢

**Comment by chengyuhang** [comment]
你需要判断下你的lrc文件是否被下载下来或者能否被读取

**Comment by CoolEnoughSmile** [comment]
我先调用了loadLrc方法后，再调用hasLrc方法返回false，是什么原因呢？我设置的是String类型，同样的字符串我在你的demo里就可以显示出来，但我的项目里不出来

**Comment by wangchenyan** [comment]
@CoolEnoughSmile 根据你的描述应该是歌词文本格式不正确，导致解析失败，可参考demo中的格式格式。
