### ISSUE TITLE
歌词不能拖动

### ISSUE THREAD

**Issue by wanghaoxin20** [wangchenyan/lrcview#29]
歌词正常显示,但是却不能拖动

**Comment by 447zyg** [comment]
/**
     * 设置播放按钮点击监听器
     *
     * @param onPlayClickListener 如果为非 null ，则激活歌词拖动功能，否则将将禁用歌词拖动功能
     */
    public void setOnPlayClickListener(OnPlayClickListener onPlayClickListener) {
        mOnPlayClickListener = onPlayClickListener;
    }

**Comment by wangchenyan** [comment]
> ```
>  /**
>  * 设置播放按钮点击监听器
>  *
>  * @param onPlayClickListener 如果为非 null ，则激活歌词拖动功能，否则将将禁用歌词拖动功能
>  */
> public void setOnPlayClickListener(OnPlayClickListener onPlayClickListener) {
>     mOnPlayClickListener = onPlayClickListener;
> }
> ```

正解
