### ISSUE TITLE
lrcEntry 高度计算问题

### ISSUE THREAD

**Issue by Voidruiyi** [wangchenyan/LrcView#3]
LrcEntry 高度计算存在问题， 您未把行间距计算在内，行数多了，会存在重叠问题
float getTextHeight() {
        if (paint == null || staticLayout == null) {
            return 0;
        }
        return staticLayout.getLineCount() * paint.getTextSize();   // 此时行间距为1.0f,
    }

**Comment by Voidruiyi** [comment]
共勉

**Comment by Voidruiyi** [comment]
共勉

**Comment by wangchenyan** [comment]
@Voidruiyi 谢谢指正！
