### ISSUE TITLE
关于“二分法查找当前时间应该显示的行数”

### ISSUE THREAD

**Issue by ccmoniter** [wangchenyan/lrcview#31]
private int findShowLine(long time) {

        int left = 0;
        int right = mLrcEntryList.size();

        while (left <= right) {
            int middle = (left + right) / 2;
            long middleTime = mLrcEntryList.get(middle).getTime();

            if (time < middleTime) {
                right = middle - 1;
            } else {
                if (middle + 1 >= mLrcEntryList.size() || time < mLrcEntryList.get(middle + 1).getTime()) {
                    return middle;
                }
                left = middle + 1;
            }
        }
        return 0;
    }
你好，请问 “middle + 1 >= mLrcEntryList.size()”这段代码中可不可以把mLrcEntryList.size()换成right ?

**Comment by wangchenyan** [comment]
应该是可以的，建议测试一下

**Comment by zorozhao** [comment]
不可以，while 中right 是>=mLrcEntryList.size()。
