### ISSUE TITLE
歌词只支持 UTF-8格式的吗？

### ISSUE THREAD

**Issue by yiran1020** [wangchenyan/lrcview#33]
如题，歌词文件只支持UTF-8 格式吗？GBK会出现乱码

**Comment by yiran1020** [comment]
问题解决了，读取歌词文件的时候 设置了一下 读取编码 感谢~

**Comment by coder-pig** [comment]
> 问题解决了，读取歌词文件的时候 设置了一下 读取编码 感谢~

您好，请问歌词文件怎么设置读取编码模式？没看到loadLrc提供这个字段

**Comment by yiran1020** [comment]
我修改源码了，默认是只支持utf8 的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coder-pig"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五)我是 中午12:19
收件人:&nbsp;"wangchenyan/lrcview"<lrcview@noreply.github.com&gt;;
抄送:&nbsp;"我的ID是淡然一笑"<1465316308@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wangchenyan/lrcview] 歌词只支持 UTF-8格式的吗？ (#33)





  
问题解决了，读取歌词文件的时候 设置了一下 读取编码 感谢~
  
您好，请问歌词文件怎么设置读取编码模式？没看到loadLrc提供这个字段

**Comment by coder-pig** [comment]
> 我修改源码了，默认是只支持utf8 的 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Coder-pig"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月13日(星期五)我是 中午12:19 收件人:&nbsp;"wangchenyan/lrcview"<lrcview@noreply.github.com&gt;; 抄送:&nbsp;"我的ID是淡然一笑"<1465316308@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [wangchenyan/lrcview] 歌词只支持 UTF-8格式的吗？ (#33) 问题解决了，读取歌词文件的时候 设置了一下 读取编码 感谢~ 您好，请问歌词文件怎么设置读取编码模式？没看到loadLrc提供这个字段 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

能加下QQ交流下吗？感谢~

**Comment by yiran1020** [comment]
我的qq 1465316308，互相交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coder-pig"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 中午1:51
收件人:&nbsp;"wangchenyan/lrcview"<lrcview@noreply.github.com&gt;;
抄送:&nbsp;"我的ID是淡然一笑"<1465316308@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wangchenyan/lrcview] 歌词只支持 UTF-8格式的吗？ (#33)





  
我修改源码了，默认是只支持utf8 的 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Coder-pig"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月13日(星期五)我是 中午12:19 收件人:&nbsp;"wangchenyan/lrcview"<lrcview@noreply.github.com&gt;; 抄送:&nbsp;"我的ID是淡然一笑"<1465316308@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [wangchenyan/lrcview] 歌词只支持 UTF-8格式的吗？ (#33) 问题解决了，读取歌词文件的时候 设置了一下 读取编码 感谢~ 您好，请问歌词文件怎么设置读取编码模式？没看到loadLrc提供这个字段 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
能加下QQ交流下吗？感谢~
