### ISSUE TITLE
请添加一个单击事件可以吗？

### ISSUE THREAD

**Issue by ruanbaojun1105** [wangchenyan/lrcview#36]
感觉作者开源
希望增加控件单击事件，谢谢

**Comment by wangchenyan** [comment]
@ruanbaojun1105 你好，能详细表述下需求吗？具体是什么单击事件

**Comment by ruanbaojun1105** [comment]
就像网易云的操作一样，点击封面就显示歌词，点了歌词就返回封面，现在的问题是开启了手势就把单击事件消费了，自己懒就想着让你加个哈哈

**Comment by wangchenyan** [comment]
@ruanbaojun1105 好的，我这两天加一下

**Comment by SUHONGJIN** [comment]
大佬，写好了吗，等用

**Comment by SUHONGJIN** [comment]
> @ruanbaojun1105 好的，我这两天点击事件做好了吗大佬

**Comment by ruanbaojun1105** [comment]
@SUHONGJIN 急着用自己写一下嘛

**Comment by KotlinLan** [comment]
@ruanbaojun1105 请问怎么实现这个功能，试了没成功，谢谢

**Comment by ruanbaojun1105** [comment]
@KotlinLan https://github.com/ruanbaojun1105/lrcview
