### ISSUE TITLE
发现BUG 了

### ISSUE THREAD

**Issue by HolaChang** [wangchenyan/lrcview#41]
Accessing hidden field Landroid/animation/ValueAnimator;->sDurationScale:F (greylist-max-p, reflection, denied)
W/System.err: java.lang.NoSuchFieldException: No field sDurationScale in class Landroid/animation/ValueAnimator; (declaration of 'android.animation.ValueAnimator' appears in /system/framework/framework.jar)
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
        at me.wcy.lrcview.LrcUtils.resetDurationScale(LrcUtils.java:214)
        at me.wcy.lrcview.LrcView.smoothScrollTo(LrcView.java:653)
        at me.wcy.lrcview.LrcView.smoothScrollTo(LrcView.java:633)
        at me.wcy.lrcview.LrcView.access$800(LrcView.java:47)
        at me.wcy.lrcview.LrcView$5.run(LrcView.java:382)
        at me.wcy.lrcview.LrcView.runOnUi(LrcView.java:733)

**Comment by wangchenyan** [comment]
@HolaChang 请问机型、系统版本是什么？

**Comment by wangchenyan** [comment]
@HolaChang 看了下这个属性在 Android 10 以后被禁用了，会有错误日志打出来，不影响正常使用

**Comment by HolaChang** [comment]
华为  安卓10Q  这个BUG我仔细看了一下源代码，发现是调用了反射重新定义私有属性报的错，按道理来讲不应该出现这种错误，的确是调用的 getDeclared，虽然能正常运行，但是会在运行过程中抛出异常，同时我也发现，可以不调用那个方法去重新定义值（删掉那个函数后目前能够正常运行）。麻烦大佬了😬------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chay&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月21日(星期一) 上午10:52
收件人:&nbsp;&quot;wangchenyan/lrcview&quot;<lrcview@noreply.github.com&gt;;
抄送:&nbsp;&quot;HolaChang&quot;<2485548477@QQ.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangchenyan/lrcview] 发现BUG 了 (#41)
