### ISSUE TITLE
调整切换速度

### ISSUE THREAD

**Issue by JackuXL** [wangchenyan/lrcview#44]
感觉切换速度慢慢划贼难受
能不能整个自定义的

**Comment by wangchenyan** [comment]
@JackuXL 你说的是歌词滚动吗？歌词滚动支持跟手和fling，问题能描述的具体点吗？

**Comment by JackuXL** [comment]
比如说从00:01到00:02，是从00:01开始以匀速滚动，如果间隔时间长就很难受，比如说可以调整从00:01:30开始到00:02之类的
