### ISSUE TITLE
loadLrcByUrl概率性加载时间过长的问题

### ISSUE THREAD

**Issue by dlisagod** [wangchenyan/lrcview#45]
我看源码里用的HttpUrlConnection加载有时候时间会特别长，导致加载不出来。是不是HttpUrlConnection的问题

**Comment by dlisagod** [comment]
先记录一下，经过多番测试，当发生这种加载不出或者加载时间过长情况，出现在loadLrcByUrl的AsyncTask里面，没有执行doInBackground。

**Comment by wangchenyan** [comment]
@dlisagod 如果觉得 HttpUrlConnection 比较慢的话也可以使用 APP 的网络请求库请求歌词文本，然后通过 `loadLrc(String lrcText)` 加载歌词

**Comment by dlisagod** [comment]
@wangchenyan 测试了很久，发现不是HttpUrlConnection的问题，是AsyncTask的问题，它自己有个线程池。我换了其它的方法。这个只是给你提供点参考，这个bug很少会遇到的，不过因为机器性能和产品需求会经常用Lrc加载就偶发遇到了这个问题

**Comment by wangchenyan** [comment]
@dlisagod 感谢反馈 🤝
