### ISSUE TITLE
频繁切换歌词，换行失效，歌词超出屏幕

### ISSUE THREAD

**Issue by paihuai00** [wangchenyan/lrcview#46]
前提：oppo手机(出现概率较大)

问题：歌词换行失效。

操作：频繁进行歌曲切换，调用`loadLrc(File lrcFile)` 加载歌词。偶现折行失效的bug，导致歌词超出屏幕被裁剪。

不知道是否有人遇到过这个问题

**Comment by wangchenyan** [comment]
@paihuai00 你好，请问是否可以提供具体机型和截图，以便排查问题

**Comment by paihuai00** [comment]
折行失效、和当前行字体变大，内容超出区域。看了一下是  width 导致的问题，我在 onDraw 绘制当前行的时候，重新调用了一下 `LrcEntry#init` 方法，解决了该问题。

**Comment by bdohBird** [comment]
> 折行失效、和当前行字体变大，内容超出区域。看了一下是 width 导致的问题，我在 onDraw 绘制当前行的时候，重新调用了一下 `LrcEntry#init` 方法，解决了该问题。

你好，这个具体是怎么解决的，有代码么？
