### ISSUE TITLE
jitpack.io上的包有bug

### ISSUE THREAD

**Issue by CureMosquito** [wangchenyan/lrcview#49]
implementation 'me.wcy:lrcview:2.2'
![image](https://user-images.githubusercontent.com/42987674/133404160-a70e7ebc-5273-40a7-964f-f11bbd6f6b3a.png)
这段代码明显和GitHub上的代码不一样，而且有滑动问题
你是不是推错包了

**Comment by wangchenyan** [comment]
@CureMosquito 抱歉，目前 JitPack 无法登录，等恢复之后我再发布一次

**Comment by wangchenyan** [comment]
@CureMosquito 已发布 com.github.wangchenyan:lrcview:2.2.1，麻烦再试一下
