### ISSUE TITLE
How to Change Text Color programmatically?

### ISSUE THREAD

**Issue by htqqdd** [wangchenyan/LrcView#9]
How to Change Text Color programmatically instead of Xml?

**Comment by wangchenyan** [comment]
@htqqdd I am sorry to tell you that there is no way to Change Text Color programmatically, if you need, I will add it on the next release, thank you!

**Comment by htqqdd** [comment]
really looking forward your updates！

**Comment by wangchenyan** [comment]
@htqqdd Hi, I have added the methods, please upgrade to version 1.4.3, thanks!
